[2023-05-13T09:51:25.727+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: greenery_addresses_data_pipeline.extract_data manual__2023-05-13T09:51:24.838172+00:00 [queued]>
[2023-05-13T09:51:25.735+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: greenery_addresses_data_pipeline.extract_data manual__2023-05-13T09:51:24.838172+00:00 [queued]>
[2023-05-13T09:51:25.736+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T09:51:25.736+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-13T09:51:25.737+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T09:51:25.745+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): extract_data> on 2023-05-13 09:51:24.838172+00:00
[2023-05-13T09:51:25.752+0000] {standard_task_runner.py:55} INFO - Started process 12197 to run task
[2023-05-13T09:51:25.755+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'greenery_addresses_data_pipeline', 'extract_data', 'manual__2023-05-13T09:51:24.838172+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/greenery_addresses_data_pipeline.py', '--cfg-path', '/tmp/tmp4t1p8k2w']
[2023-05-13T09:51:25.768+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask extract_data
[2023-05-13T09:51:25.839+0000] {task_command.py:389} INFO - Running <TaskInstance: greenery_addresses_data_pipeline.extract_data manual__2023-05-13T09:51:24.838172+00:00 [running]> on host 81a59154956d
[2023-05-13T09:51:25.893+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=greenery_addresses_data_pipeline
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-05-13T09:51:24.838172+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-13T09:51:24.838172+00:00
[2023-05-13T09:51:25.895+0000] {logging_mixin.py:137} INFO - ##### Start get data from API #####
[2023-05-13T09:51:26.118+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/greenery_addresses_data_pipeline.py", line 25, in _extract_data
    with open(f"{DATA_FOLDER}/addresses.csv", "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/addresses.csv'
[2023-05-13T09:51:26.140+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=greenery_addresses_data_pipeline, task_id=extract_data, execution_date=20230513T095124, start_date=20230513T095125, end_date=20230513T095126
[2023-05-13T09:51:26.152+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 10 for task extract_data ([Errno 2] No such file or directory: 'data/addresses.csv'; 12197)
[2023-05-13T09:51:26.184+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-13T09:51:26.205+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
