[2023-05-13T09:50:04.490+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: greenery_addresses_data_pipeline.extract_data manual__2023-05-13T09:49:32.951213+00:00 [queued]>
[2023-05-13T09:50:04.496+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: greenery_addresses_data_pipeline.extract_data manual__2023-05-13T09:49:32.951213+00:00 [queued]>
[2023-05-13T09:50:04.497+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T09:50:04.498+0000] {taskinstance.py:1289} INFO - Starting attempt 3 of 3
[2023-05-13T09:50:04.499+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T09:50:04.508+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): extract_data> on 2023-05-13 09:49:32.951213+00:00
[2023-05-13T09:50:04.517+0000] {standard_task_runner.py:55} INFO - Started process 11730 to run task
[2023-05-13T09:50:04.522+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'greenery_addresses_data_pipeline', 'extract_data', 'manual__2023-05-13T09:49:32.951213+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/greenery_addresses_data_pipeline.py', '--cfg-path', '/tmp/tmphih24leo']
[2023-05-13T09:50:04.526+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask extract_data
[2023-05-13T09:50:04.596+0000] {task_command.py:389} INFO - Running <TaskInstance: greenery_addresses_data_pipeline.extract_data manual__2023-05-13T09:49:32.951213+00:00 [running]> on host 81a59154956d
[2023-05-13T09:50:04.654+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=greenery_addresses_data_pipeline
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-05-13T09:49:32.951213+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-13T09:49:32.951213+00:00
[2023-05-13T09:50:04.657+0000] {logging_mixin.py:137} INFO - ##### Start get data from API #####
[2023-05-13T09:50:04.907+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/greenery_addresses_data_pipeline.py", line 25, in _extract_data
    with open(f"{DATA_FOLDER}/addresses.csv", "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/addresses.csv'
[2023-05-13T09:50:04.937+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=greenery_addresses_data_pipeline, task_id=extract_data, execution_date=20230513T094932, start_date=20230513T095004, end_date=20230513T095004
[2023-05-13T09:50:04.951+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 9 for task extract_data ([Errno 2] No such file or directory: 'data/addresses.csv'; 11730)
[2023-05-13T09:50:04.989+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-13T09:50:05.010+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
