[2023-05-14T05:44:25.766+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: greenery_addresses_data_pipeline.load_data_to_gcs manual__2023-05-14T05:44:23.238480+00:00 [queued]>
[2023-05-14T05:44:25.774+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: greenery_addresses_data_pipeline.load_data_to_gcs manual__2023-05-14T05:44:23.238480+00:00 [queued]>
[2023-05-14T05:44:25.775+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-14T05:44:25.777+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-14T05:44:25.778+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-14T05:44:25.787+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): load_data_to_gcs> on 2023-05-14 05:44:23.238480+00:00
[2023-05-14T05:44:25.792+0000] {standard_task_runner.py:55} INFO - Started process 8914 to run task
[2023-05-14T05:44:25.797+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'greenery_addresses_data_pipeline', 'load_data_to_gcs', 'manual__2023-05-14T05:44:23.238480+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/greenery_addresses_data_pipeline.py', '--cfg-path', '/tmp/tmp5311h_n0']
[2023-05-14T05:44:25.798+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask load_data_to_gcs
[2023-05-14T05:44:25.882+0000] {task_command.py:389} INFO - Running <TaskInstance: greenery_addresses_data_pipeline.load_data_to_gcs manual__2023-05-14T05:44:23.238480+00:00 [running]> on host 81a59154956d
[2023-05-14T05:44:25.937+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=greenery_addresses_data_pipeline
AIRFLOW_CTX_TASK_ID=load_data_to_gcs
AIRFLOW_CTX_EXECUTION_DATE=2023-05-14T05:44:23.238480+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-14T05:44:23.238480+00:00
[2023-05-14T05:44:25.940+0000] {logging_mixin.py:137} INFO - ##### Start upload data: addresses , date: 2023-05-14 to GCS #####
[2023-05-14T05:44:25.942+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/greenery_addresses_data_pipeline.py", line 57, in _load_data_to_gcs
    service_account_info_gcs = json.load(open(keyfile_gcs))
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/dataengineer-service-account-gcs.json'
[2023-05-14T05:44:25.952+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=greenery_addresses_data_pipeline, task_id=load_data_to_gcs, execution_date=20230514T054423, start_date=20230514T054425, end_date=20230514T054425
[2023-05-14T05:44:25.960+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 21 for task load_data_to_gcs ([Errno 2] No such file or directory: '/opt/airflow/dags/data/dataengineer-service-account-gcs.json'; 8914)
[2023-05-14T05:44:26.009+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-14T05:44:26.030+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
